# CybersecurityChatbot

name: C# CI workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "CybersecurityChatbot.sln"

      - name: Check Code Formatting
        run: dotnet format --verify-no-changes "CybersecurityChatbot.sln" || exit 1

      - name: Build Project
        run: msbuild "CybersecurityChatbot.sln" /p:Configuration=Release
